package com.example.sp.common.error.model;

public enum ErrorCode {
    NO_USER_WITH_GIVEN_ID_ERROR,
    USER_WITH_GIVEN_ID_HAVE_IMAGE_ALREADY_ASSIGNED_ERROR,
    NO_IMAGE_FOR_GIVEN_USER,
    NO_USER_PREFERENCES_FOR_GIVEN_USER_ERROR
}
